import '@/assets/styles/globals.scss';
import { WeatherProvider } from '@/contexts/WeatherContext/WeatherContextProvider';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <WeatherProvider>{children}</WeatherProvider>
      </body>
    </html>
  );
}
